### ISSUE TITLE
请问可以添加一个功能吗：通过快捷键隐藏其他窗口元素（保留黑色背景+字幕+注音）

### ISSUE THREAD

**Issue by ads233** [ks233/ja-learner#18]
我想把ja-learner作为一个沉浸式的纯字幕+注音显示软件，像下面这样
![截图_20240220170135](https://github.com/ks233/ja-learner/assets/153071412/02409562-b194-48b3-9732-3213ba0ba61c)
：

**Comment by ks233** [comment]
做好了，双击背景进入沉浸模式，ctrl+左键拖动窗口
https://github.com/ks233/ja-learner/releases/tag/release-2024%E5%B9%B402%E6%9C%8820%E6%97%A5140917

**Comment by ads233** [comment]
不知道怎么回事，出现错误如下
![Uploading 截图_20240220223242.png…]()

**Comment by ads233** [comment]
![2](https://github.com/ks233/ja-learner/assets/153071412/f2042e14-58bb-4efe-948f-bcdd080b0e82)

**Comment by ks233** [comment]
怪了，这和上个版本也没太大区别啊，我自己电脑上也能直接解压运行，会不会是哪个文件被杀毒软件误删了

**Comment by ads233** [comment]
可能是我电脑问题.........我再测试一下

**Comment by ads233** [comment]
我暂时不懂怎么把自动复制字幕到粘贴板的功能增添到懒人包MPV程序里，要是成功的话使用这个网站可以获取很多动漫的日文字幕https://kitsunekko.net/另外我结合其他人的项目制作了一款只需要提交网页视频地址（大多数网站都可以用）就可以运用whisper X进行转录字幕的谷歌colab的notebook：https://colab.research.google.com/drive/1FrKV1TFra5joJ8tRI8zwTTuMQGj5WugH#scrollTo=96sSsfsBkYOD

**Comment by ads233** [comment]
昨晚老是报错，今天早上起来试了一下又恢复正常能用了，不知道我的电脑发什么神经病……

**Comment by ads233** [comment]
这个免费的OCR准确度挺好的！要是这个OCR软件能自动发送文本到粘贴板的话就好了https://github.com/Danily07/Translumo

**Comment by ads233** [comment]
不知道MPV是不是要安装这个才能实现将字幕自动发送到电脑的粘贴板https://gist.github.com/Rapptz/9664773178da1bc397cf
