### ISSUE TITLE
谷歌翻译失败后程序崩溃

### ISSUE THREAD

**Issue by Landius** [ks233/ja-learner#21]
由于GFW的缘故，在大陆无法直接访问谷歌翻译，不使用代理的话会翻译失败并导致直接崩溃。
目前好像只能通过改系统全局代理来使用谷歌翻译，希望可以在程序设置里增加单独的代理设置。

**Comment by ks233** [comment]
感谢反馈！刚刚试了一下确实会闪退，我这梯子平时一直开着所以没注意到，有空修一下

现在可以先用 https://github.com/GoodCoder666/GoogleTranslate_IPFinder 找个墙内可用的ip，然后改host就能用了，以后可能会加个设置谷歌翻译ip的功能

**Comment by Landius** [comment]
> 加个设置谷歌翻译ip的功能

感觉加个代理设置会好点？
因为 `api.openai.com` 也是需要代理才能访问的。

**Comment by ks233** [comment]
为啥要单独设置代理，一般正常开着梯子就能用啊，你用的梯子设置比较麻烦吗

**Comment by ks233** [comment]
刚刚问了隔壁issue #22，终于知道代理是咋回事了，原来大伙平时都不开系统代理的吗（

下个版本应该能把代理安排上，感谢建议！

**Comment by Landius** [comment]
> 为啥要单独设置代理，一般正常开着梯子就能用啊，你用的梯子设置比较麻烦吗
> 
> 我对网络代理这块不太了解，不知道你需要的代理功能大概长啥样？

主要是开了全局代理的话，会导致一些不需要代理的软件也走代理，虽说可以通过规则分流，但总归是多套一层娃😂

**Comment by ks233** [comment]
更新了，修复了闪退bug，加了http代理功能，我自己试了谷歌翻译代理可以用，gpt我只有不需要梯子的第三方api没法测试，如果你有需要梯子的api能帮我试一下吗？感谢！

https://github.com/ks233/ja-learner/releases/tag/v0.4

**Comment by Landius** [comment]
> 更新了，修复了闪退bug，加了http代理功能，我自己试了谷歌翻译代理可以用，gpt我只有不需要梯子的第三方api没法测试，如果你有需要梯子的api能帮我试一下吗？感谢！
> 
> https://github.com/ks233/ja-learner/releases/tag/v0.4

辛苦了~

刚刚试了一下，新加的 checkbox 是灰色的无法选中
![图片](https://github.com/ks233/ja-learner/assets/11910028/ea39f5c9-1aca-4d8f-a46f-c4c1e77e49b4)


要编辑 `appsettings.json` 里的 `HttpProxy` 的值不为空才能勾选
![图片](https://github.com/ks233/ja-learner/assets/11910028/238ce55f-7ffd-4035-8c96-695c442334e4)


应该是这里的问题？
https://github.com/ks233/ja-learner/blob/bfeab8f773c09b8ad79cd3678468ab9a270569eb/GUI/MainForm.Designer.cs#L94

**Comment by ks233** [comment]
确实，忘记说明了

现在只有读json的功能，还不能在软件里改设置，以后加上写json的功能就能保存状态了
