### ISSUE TITLE
有几个问题

### ISSUE THREAD

**Issue by lhj5426** [ks233/ja-learner#22]
在GITHUB首页右下角的探索仓库推荐里发现的大佬的作品然后有一些问题
![image](https://github.com/ks233/ja-learner/assets/30548000/47333489-5686-4c6d-998e-cacc8b439ee7)
1 可以 手动设置端口嘛 
2 GPT 可以设置第三方API嘛 
![image](https://github.com/ks233/ja-learner/assets/30548000/6b01b179-d988-4d42-a423-bdf91f12af9e)
3 可以设置自定义代理吗？

**Comment by ks233** [comment]
1. 端口还不能手动设置，目前只能默认8080，如果被占用了会自动往后找，我觉得确实可以加个手动设置端口的选项
2. 第三方api如果url后缀格式和调用方法都和官方一样是可以调用的
 
默认调用的是`https://api.openai.com/v1/chat/completions`，设置文件里写的是`https://api.openai.com/{0}/{1}`，如果要调用的第三方api是`https://api.xxxx.com/v1/chat/completions`，在设置文件里改成`https://api.xxxx.com/{0}/{1}`就行，但如果url后缀不是`/v1/chat/completions`就不能调用了

**Comment by lhj5426** [comment]
> 1. 端口还不能手动设置，目前只能默认8080，如果被占用了会自动往后找，我觉得确实可以加个手动设置端口的选项
> 2. 第三方api如果url后缀格式和调用方法都和官方一样是可以调用的
> 
> 默认调用的是`https://api.openai.com/v1/chat/completions`，设置文件里写的是`https://api.openai.com/{0}/{1}`，如果要调用的第三方api是`https://api.xxxx.com/v1/chat/completions`，在设置文件里改成`https://api.xxxx.com/{0}/{1}`就行，但如果url后缀不是`/v1/chat/completions`就不能调用了
> 
> _代理_是指访问外网吗？上一个issue也建议加个_代理_功能，但这块我真的不太了解，我自己是普通地开着_梯子_软件用的，不知道你需要什么样的_代理_功能？

一般只开仅代理 谁用谁调用 既搀和系统也不是全局
![image](https://github.com/ks233/ja-learner/assets/30548000/52107165-c127-4f1f-b752-cfd32924e439)

![image](https://github.com/ks233/ja-learner/assets/30548000/ca0a0aea-552e-45f3-a792-4709d645974b)

![image](https://github.com/ks233/ja-learner/assets/30548000/6336873b-bf12-4a8b-a701-6c6890134ebb)

 这样

**Comment by ks233** [comment]
ok，懂了，我参考下，下个版本看看能不能安排上
~~原来一直开着系统代理的只有我吗~~

**Comment by ks233** [comment]
更新了，加了http代理功能，我自己试了谷歌翻译代理可以用，gpt我只有不需要梯子的第三方api没法测试，如果你有需要梯子的api能帮我试一下吗？感谢！

https://github.com/ks233/ja-learner/releases/tag/v0.4

**Comment by lhj5426** [comment]
> 更新了，加了http_代理_功能，我自己试了谷歌翻译_代理_可以用，_gpt_我只有不需要_梯子_的第三方api没法测试，如果你有需要_梯子_的api能帮我试一下吗？感谢！
> 
> [https://github.com/ks233/ja-learner/_releases_/tag/v0.4](https://github.com/ks233/ja-learner/releases/tag/v0.4)

嗯 代理没问题可以使用
![image](https://github.com/ks233/ja-learner/assets/30548000/33028b43-a28f-483d-b488-d73629ef511f)
就是 这个 分析 可以自动分析吗？
![image](https://github.com/ks233/ja-learner/assets/30548000/7d93fa5f-f9bd-4822-bc31-57fd2d43bc17)

**Comment by ks233** [comment]
自动分析的需求应该不多，暂时不考虑，以后把gpt界面改成webview了可能会加这个选项

gpt代理能用我就放心了，谢谢老哥帮忙测试~

**Comment by lhj5426** [comment]
> 自动分析的需求应该不多，暂时不考虑，以后把_gpt_界面改成webview了可能会加这个选项
> 
> _gpt__代理_能用我就放心了，谢谢老哥帮忙测试~

应该谢谢你才对 嗯 
我把 大佬的JSON的提示词直接拿走放在gpt里用也行哈哈
![image](https://github.com/ks233/ja-learner/assets/30548000/ba8466e9-fa55-4eb1-9d7a-a70340f3921a)
