### ISSUE TITLE
bug: 词典结果未显示

### ISSUE THREAD

**Issue by hundun000** [ks233/ja-learner#33]
复现：
v0.4 任意句子 左键查词 不论是否首次查询，均结果未显示

log：
网络请求成功；再次查询有命中缓存日志；

![image](https://github.com/user-attachments/assets/9e6c8533-b41b-42a9-9871-e91ac3d394d3)

**Comment by hundun000** [comment]
调试看了下，看来是因为：

https://github.com/ks233/ja-learner-webview/blob/8a8f146a7eeb4cd0211fa645dd2d9177ca944ceb/src/views/DictView.vue#L139

使value变为空

**Comment by ks233** [comment]
感谢反馈！好久没维护了，可能moji接口变了，有空看下

**Comment by ks233** [comment]
刚发了个更新，把那行filter去掉就好了，感谢~
