### ISSUE TITLE
请教天使 reboot 那个是个什么软件

### ISSUE THREAD

**Issue by vdzh** [ks233/ja-learner#7]
感谢 做出这样的工具！

请教天使 reboot 那个是个什么软件，是游戏吗，还是个漫画阅读器。

想请教一下如何下载。
如图日语来源的那个窗口
![attach](https://github.com/ks233/ja-learner/assets/145197556/2cc0e975-89fc-4ddb-93c8-13195643bc92)

**Comment by vdzh** [comment]
抱歉打扰，自行查询了一下是游戏也有同步发行的漫画，搜索了很多下载都是汉化过的，请问大佬有未汉化的游戏版本吗。

**Comment by ks233** [comment]
> 抱歉打扰，自行查询了一下是游戏也有同步发行的漫画，搜索了很多下载都是汉化过的，请问大佬有未汉化的游戏版本吗。

生肉资源在外网还是挺好找的，比如到[ggbases](https://www.ggbases.com/)搜索磁力链接下载。

这些和项目本身没啥关系，其它问题就自行google吧（
