### ISSUE TITLE
Autobuild fails due to no access

### ISSUE THREAD

**Issue by ly-nld** [ks233/ja-learner#8]
#4 

https://github.com/ks233/ja-learner/actions/runs/7361381099/job/20038630800#step:11:11
The action has no permissions. You can give them permission here:
https://github.com/ks233/ja-learner/settings/actions

![afbeelding](https://github.com/ks233/ja-learner/assets/38471793/ad8068e6-25b1-46fa-bc38-11d0d046dc53)

**Comment by ks233** [comment]
It works fine now! Thank you!!!
How can I manage branches? Is it appropriate to create a 'dev' branch and set it as the default, then merge it into 'main' when updating to a new version?

**Comment by ly-nld** [comment]
> It works fine now! Thank you!!! How can I manage branches? Is it appropriate to create a 'dev' branch and set it as the default, then merge it into 'main' when updating to a new version?

Yes that would be the best thing to do. I would also recommend setting up "Branch Protection Rules" for the "main" branch to require the build in "dev" to be successful.
